trigger:
- none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'my-container-app'
  dockerHubRepo: 'docker.io/expertpcin/my-container-app'
  containerAppNameDev: 'my-container-app-dev'
  containerAppNameTest: 'my-container-app-test'
  resourceGroup: 'rg'
  location: 'westeurope'

stages:
- stage: Build
  displayName: Build and push image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: default
    steps:
    - task: Docker@2
      displayName: Build and push an image
      inputs:
        command: buildAndPush
        dockerfile: /Dockerfile
        repository: $(dockerHubRepo)
        tags: $(tag)

- stage: Deploy
  displayName: Deploy to Container Apps
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      name: default
    steps:
    - task: AzureCLI@2
      displayName: Deploy new container version
      inputs:
        azureSubscription: 'SkyNetLab(5ed968f6-a0e5-49c9-897b-ab7eb32ea028)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az containerapp update --name $(containerAppNameDev) --resource-group $(resourceGroup) --image $(dockerHubRepo):$(tag) --ingress external --target-port 3500'