---
- name: Install Azure CLI
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Import Microsoft repository signing key
      ansible.builtin.apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Manually specify distribution codename for Azure CLI repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ noble main"
        state: present
        update_cache: yes

    - name: Install Azure CLI
      ansible.builtin.apt:
        name: azure-cli
        state: latest
        update_cache: yes
